<?php
/**
 * Bialsoft_Cmspro extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the GPL License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/gpl-license.php
 * 
 * @category       Bialsoft
 * @package        Bialsoft_Cmspro
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Category children list template
 *
 * @category    Bialsoft
 * @package     Bialsoft_Cmspro

 */
?>
<?php $_cmscategories = $this->getCmscategories(); ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php if ($_cmscategories->getSize() > 0) : ?>

    <div class="category-products">
        <ol class="products-list" id="products-list" style="margin-top: 0px;">
            <?php foreach ($_cmscategories as $_cmscategory) : ?>
                <li class="item">
                    <h3><a href="<?php echo $_cmscategory->getCmscategoryUrl() ?>"><?php echo $_cmscategory->getTitle(); ?></a></h3>

                    <?php if ($_cmscategory->getImage()) : ?>
                        <p class="category-image">

                            <a href="<?php echo $_cmscategory->getCmscategoryUrl() ?>"><img src="<?php
                                echo Mage::helper('bialsoft_cmspro/cmscategory_image')->init($_cmscategory,
                                    'image');
                                ?>" alt="<?php echo $this->escapeHtml($_cmscategory->getTitle()); ?>" />

                            </a>
                        </p>
                    <?php endif; ?>

                    <div class="category-description std">
                        <?php echo $_cmscategory->getDescription(); ?>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>

<?php endif; ?>
