<?php
/**
 * Bialsoft_Cmspro extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the GPL License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/gpl-license.php
 * 
 * @category       Bialsoft
 * @package        Bialsoft_Cmspro
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Category children list template
 *
 * @category    Bialsoft
 * @package     Bialsoft_Cmspro
 
 */
?>
<?php $_cmscategories = $this->getCmscategories(); ?>
<?php if ($_cmscategories->getSize() > 0) : ?>
    <div class="page-title category-title">
        <h2><?php echo $this->getCurrentCmscategory()->getTitle(); ?>:<?php echo $this->__('Children') ?></h2>
    </div>
    <?php if ($this->_getDisplayMode() == 0) : ?>
        <div class="cmscategory-list-container">
            <?php foreach ($_cmscategories as $_cmscategory) : ?>
                <div class="cmscategory-list-item">
                    <a href="<?php echo $_cmscategory->getCmscategoryUrl(); ?>" title="<?php echo $this->escapeHtml($_cmscategory->getTitle()) ?>">
                        <?php echo $_cmscategory->getTitle(); ?>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
    <?php else : ?>
        <ul id="cmscategories-list">
            <?php foreach ($_cmscategories as $_cmscategory) : ?>
                <?php echo $this->drawCmscategory($_cmscategory); ?>
            <?php endforeach; ?>
        </ul>
        <script type="text/javascript">
            cmsproTree('cmscategories-list');
        </script>
    <?php endif; ?>
<?php endif; ?>
