<?php
/**
 * Bialsoft_Cmspro extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the GPL License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/gpl-license.php
 * 
 * @category       Bialsoft
 * @package        Bialsoft_Cmspro
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Category view template
 *
 * @category    Bialsoft
 * @package     Bialsoft_Cmspro

 */
?>
<?php $_cmscategory = $this->getCurrentCmscategory(); ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title category-title">
    <h1><?php echo $_cmscategory->getTitle(); ?></h1>
</div>
<?php if ($_cmscategory->getImage()) : ?>
    <p class="category-image">

        <img src="<?php
        echo Mage::helper('bialsoft_cmspro/cmscategory_image')->init($_cmscategory,
            'image');
        ?>" alt="<?php echo $this->escapeHtml($_cmscategory->getTitle()); ?>" />


    </p>
<?php endif; ?>

<div class="category-description std">
    <?php echo $_cmscategory->getDescription(); ?>
</div>



