<?php
/**
 * Bialsoft_Cmspro extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the GPL License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/gpl-license.php
 * 
 * @category       Bialsoft
 * @package        Bialsoft_Cmspro
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Article comments list template
 *
 * @category    Bialsoft
 * @package     Bialsoft_Cmspro
 
 */
?>
<?php $_article = $this->getArticle() ?>
<?php if ($_article->getAllowComments()) : ?>
    <?php $_comments = $this->getComments(); ?>
    <?php if (count($_comments)) : ?>
        <br/>
        <br/>
        <h2>
            <?php echo $this->__('Comments') //echo $this->__('Comments for: %s', $_article->getTitle())     ?>
        </h2>
        <div class="box-collateral box-reviews" id="customer-reviews">











            <dl>
                <?php foreach ($_comments as $_comment): ?>
                    <dt>
                    <div class="author"><?php
                        echo $this->__('On %s %s wrote:',
                            $this->formatDate($_comment->getCreatedAt(), 'long'),
                            $this->escapeHtml($_comment->getName()))
                        ?></div>
                    <strong><?php echo $this->escapeHtml($_comment->getTitle()) ?></strong>
                    </dt>
                    <dd>
                        <?php echo nl2br($this->escapeHtml($_comment->getComment())) ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
            <div class="toolbar">
                <?php echo $this->getPagerHtml() ?>
            </div>
        </div>
    <?php endif; ?>
    <?php echo $this->getChildHtml('comment_form') ?>
<?php endif; ?>
