<?php
/**
 * Bialsoft_Cmspro extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the GPL License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/gpl-license.php
 * 
 * @category       Bialsoft
 * @package        Bialsoft_Cmspro
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Cmscategory Article list template
 *
 * @category    Bialsoft
 * @package     Bialsoft_Cmspro

 */
?>
<?php $_articles = $this->getArticles(); ?>
<?php
if ($_articles->getSize() > 0) :
    ?>
    <div class="toolbar">
        <?php echo $this->getPagerHtml(); ?>
    </div>
    <?php $_iterator = 0; ?>
    <div class="category-products">
        <ol class="products-list" id="products-list">
            <?php foreach ($_articles as $_article) : ?>




                <li class="item<?php if (++$_iterator == sizeof($_articles->getSize())): ?> last<?php endif; ?>">

                    <a href="<?php echo $_article->getArticleUrl() ?>" title="<?php echo $this->escapeHtml($_article->getTitle()); ?>" class="product-image">
                        <img src="<?php
                        echo Mage::helper('bialsoft_cmspro/article_image')->init($_article,
                            'image');
                        ?>" alt="<?php echo $this->escapeHtml($_article->getTitle()); ?>" /></a>
                        <?php // Product description    ?>
                    <div class="product-shop">
                        <div class="f-fix">

                            <h2 class="product-name"><a href="<?php echo $_article->getArticleUrl() ?>" title="<?php echo $this->escapeHtml($_article->getTitle()); ?>"><?php echo $_article->getTitle(); ?></a></h2>

                            <div class="article-description">
                                <?php
                                echo $_article->getSummary();
                                ?>

                            </div>

                        </div>
                    </div>
                </li>


            <?php endforeach; ?>
        </ol>
    </div>
    <div class="toolbar">
        <?php echo $this->getPagerHtml(); ?>
    </div>
<?php endif; ?>
