<?php
/**
 * Bialsoft_Cmspro extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the GPL License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/gpl-license.php
 * 
 * @category       Bialsoft
 * @package        Bialsoft_Cmspro
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Category link widget template
 *
 * @category    Bialsoft
 * @package     Bialsoft_Cmspro
 
 */
?>
<?php $_cmscategory = $this->getCurrentCmscategory();?>
<?php if ($_cmscategory) :?>
    <div class="cmscategory-widget-link">
        <a href="<?php echo $_cmscategory->getCmscategoryUrl()?>"><?php echo $_cmscategory->getTitle()?></a>
    </div>
<?php endif;?>
