<?php
/**
 * Bialsoft_Cmspro extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the GPL License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/gpl-license.php
 * 
 * @category       Bialsoft
 * @package        Bialsoft_Cmspro
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Category view widget template
 *
 * @category    Bialsoft
 * @package     Bialsoft_Cmspro
 
 */
?>
<?php $_cmscategory = $this->getCurrentCmscategory();?>
<?php if ($_cmscategory) :?>
    <div class="cmscategory-widget-view">
        <h3><?php echo $_cmscategory->getTitle()?></h3>
        <div>
            <div class="title-widget">
                <?php echo Mage::helper('bialsoft_cmspro')->__('Title');?>:<?php echo $_cmscategory->getTitle();?>
            </div>
            <div class="image-widget">
                <?php if ($_cmscategory->getImage()) :?>
    <img src="<?php echo Mage::helper('bialsoft_cmspro/cmscategory_image')->init($_cmscategory, 'image')->resize(75);?>" alt="<?php echo $this->escapeHtml($_cmscategory->getTitle());?>" />
<?php endif;?>
            </div>

        </div>
    </div>
<?php endif;?>
