<?php
/**
 * Bialsoft_Cmspro extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the GPL License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/gpl-license.php
 * 
 * @category       Bialsoft
 * @package        Bialsoft_Cmspro
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * cmspro rss feeds block
 * @category    Bialsoft
 * @package     Bialsoft_Cmspro
 
 */
?>
<?php $_feeds = $this->getFeeds();?>
<?php if ($_feeds): ?>
<table class="data-table rss-table" id="rss-table-cmspro" style="margin-top:20px">
    <col />
    <col width="1" />
    <thead>
        <tr>
            <th colspan="2"><?php echo Mage::helper('bialsoft_cmspro')->__('Cmspro Feeds') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($_feeds as $_feed): ?>
        <tr>
            <td><?php echo $_feed->getLabel() ?></td>
            <td><a href="<?php echo $_feed->getUrl() ?>" class="link-rss"><?php echo Mage::helper('bialsoft_cmspro')->__('Get Feed'); ?></a></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>
