<?php
/**
 * Bialsoft_Cmspro extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the GPL License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/gpl-license.php
 * 
 * @category       Bialsoft
 * @package        Bialsoft_Cmspro
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Article view template
 *
 * @category    Bialsoft
 * @package     Bialsoft_Cmspro
 
 */
?>
<?php $_article = $this->getCurrentArticle(); ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title article-title">
    <h1><?php echo $_article->getTitle(); ?></h1>
</div>

<div class="article-view  std">

    <div class="article-content">
        <?php echo $_article->getContent(); ?>

    </div>
    <!--<?php //if ($_article->getAuthor()) {  ?>
            <div class="article-author">
    <?php //echo Mage::helper('bialsoft_cmspro')->__('Author'); ?>: <?php echo $_article->getAuthor(); ?>

            </div>
    <?php //} ?>-->
</div>
